INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('01','Iana Reserved');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ac','Ascension Island');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ad','Andorra');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ae','United Arab Emirates');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('af','Afghanistan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ag','Antigua and Barbuda');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ai','Anguilla');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('al','Albania');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('am','Armenia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('an','Netherlands Antilles');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ao','Angola');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('aq','Antarctica');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ar','Argentina');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('as','American Samoa');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('at','Austria');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('au','Australia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('aw','Aruba');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ax','Aland Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('az','Azerbaijan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ba','Bosnia and Herzegovina');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bb','Barbados');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bd','Bangladesh');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('be','Belgium');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bf','Burkina Faso');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bg','Bulgaria');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bh','Bahrain');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bi','Burundi');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bj','Benin');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bl','Saint Barthelemy');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bm','Bermuda');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bn','Brunei Darussalam');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bo','Bolivia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('br','Brazil');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bs','Bahamas');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bt','Bhutan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bv','Bouvet Island');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bw','Botswana');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('by','Belarus');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('bz','Belize');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ca','Canada');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cc','Cocos (Keeling) Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cd','Congo, The Democratic Republic of the');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cf','Central African Republic');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cg','Congo');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ch','Switzerland');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ci','Cote d\'Ivoire');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ck','Cook Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cl','Chile');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cm','Cameroon');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cn','China');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('co','Colombia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cr','Costa Rica');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cu','Cuba');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cv','Cape Verde');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cx','Christmas Island');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cy','Cyprus');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('cz','Czech Republic');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('de','Germany');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('dj','Djibouti');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('dk','Denmark');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('dm','Dominica');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('do','Dominican Republic');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('dz','Algeria');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ec','Ecuador');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ee','Estonia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('eg','Egypt');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('eh','Western Sahara');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('er','Eritrea');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('es','Spain');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('et','Ethiopia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('eu','European Union');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('fi','Finland');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('fj','Fiji');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('fk','Falkland Islands (Malvinas)');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('fm','Micronesia, Federated States of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('fo','Faroe Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('fr','France');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ga','Gabon');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gb','United Kingdom');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gd','Grenada');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ge','Georgia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gf','French Guiana');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gg','Guernsey');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gh','Ghana');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gi','Gibraltar');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gl','Greenland');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gm','Gambia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gn','Guinea');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gp','Guadeloupe');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gq','Equatorial Guinea');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gr','Greece');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gs','South Georgia and the South Sandwich Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gt','Guatemala');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gu','Guam');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gw','Guinea-Bissau');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('gy','Guyana');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('hk','Hong Kong');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('hm','Heard Island and McDonald Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('hn','Honduras');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('hr','Croatia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ht','Haiti');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('hu','Hungary');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('id','Indonesia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ie','Ireland');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('il','Israel');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('im','Isle of Man');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('in','India');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('io','British Indian Ocean Territory');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('iq','Iraq');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ir','Iran, Islamic Republic of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('is','Iceland');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('it','Italy');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('je','Jersey');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('jm','Jamaica');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('jo','Jordan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('jp','Japan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ke','Kenya');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('kg','Kyrgyzstan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('kh','Cambodia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ki','Kiribati');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('km','Comoros');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('kn','Saint Kitts and Nevis');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('kp','Korea, Democratic People\'s Republic of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('kr','Korea, Republic of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('kw','Kuwait');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ky','Cayman Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('kz','Kazakhstan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('la','Lao People\'s Democratic Republic');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('lb','Lebanon');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('lc','Saint Lucia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('li','Liechtenstein');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('lk','Sri Lanka');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('lr','Liberia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ls','Lesotho');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('lt','Lithuania');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('lu','Luxembourg');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('lv','Latvia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ly','Libyan Arab Jamahiriya');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ma','Morocco');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mc','Monaco');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('md','Moldova, Republic of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('me','Montenegro');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mf','Saint Martin');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mg','Madagascar');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mh','Marshall Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mk','Macedonia, The Former Yugoslav Republic of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ml','Mali');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mm','Myanmar');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mn','Mongolia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mo','Macao');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mp','Northern Mariana Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mq','Martinique');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mr','Mauritania');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ms','Montserrat');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mt','Malta');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mu','Mauritius');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mv','Maldives');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mw','Malawi');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mx','Mexico');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('my','Malaysia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('mz','Mozambique');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('na','Namibia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('nc','New Caledonia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ne','Niger');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('nf','Norfolk Island');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ng','Nigeria');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ni','Nicaragua');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('nl','Netherlands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('no','Norway');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('np','Nepal');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('nr','Nauru');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('nu','Niue');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('nz','New Zealand');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('om','Oman');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pa','Panama');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pe','Peru');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pf','French Polynesia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pg','Papua New Guinea');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ph','Philippines');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pk','Pakistan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pl','Poland');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pm','Saint Pierre and Miquelon');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pn','Pitcairn');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pr','Puerto Rico');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ps','Palestinian Territory, Occupied');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pt','Portugal');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('pw','Palau');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('py','Paraguay');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('qa','Qatar');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('re','Reunion');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ro','Romania');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('rs','Serbia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ru','Russian Federation');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('rw','Rwanda');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sa','Saudi Arabia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sb','Solomon Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sc','Seychelles');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sd','Sudan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('se','Sweden');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sg','Singapore');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sh','Saint Helena');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('si','Slovenia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sj','Svalbard and Jan Mayen');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sk','Slovakia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sl','Sierra Leone');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sm','San Marino');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sn','Senegal');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('so','Somalia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sr','Suriname');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('st','Sao Tome and Principe');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('su','Soviet Union (being phased out)');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sv','El Salvador');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sy','Syrian Arab Republic');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('sz','Swaziland');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tc','Turks and Caicos Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('td','Chad');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tf','French Southern Territories');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tg','Togo');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('th','Thailand');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tj','Tajikistan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tk','Tokelau');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tl','Timor-Leste');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tm','Turkmenistan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tn','Tunisia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('to','Tonga');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tp','Portuguese Timor (being phased out)');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tr','Turkey');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tt','Trinidad and Tobago');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tv','Tuvalu');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tw','Taiwan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('tz','Tanzania, United Republic of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ua','Ukraine');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ug','Uganda');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('uk','United Kingdom');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('um','United States Minor Outlying Islands');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('us','United States');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('uy','Uruguay');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('uz','Uzbekistan');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('va','Holy See (Vatican City State)');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('vc','Saint Vincent and the Grenadines');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ve','Venezuela, Bolivarian Republic of');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('vg','Virgin Islands, British');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('vi','Virgin Islands, US.');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('vn','Viet Nam');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('vu','Vanuatu');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('wf','Wallis and Futuna');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ws','Samoa');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('ye','Yemen');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('yt','Mayotte');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('yu','Yugoslavia (being phased out)');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('za','South Africa');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('zm','Zambia');
INSERT INTO $prefix.`_nsnst_countries` (`c2c`, `country`) VALUES('zw','Zimbabwe');
